### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by ceblanton**
## Checklist before requesting a review

- [ ] I ran my code
- [ ] I tried to make my code readable
- [ ] I tried to comment my code
- [ ] I wrote a new test, if applicable
- [ ] I wrote new instructions/documentation, if applicable
- [ ] I ran pytest and inspected it's output
- [ ] I ran pylint and attempted to implement some of it's feedback

### CODE REVIEW

**Comment by ilaflott** [comment]
the success/fail between the two checks is awkward... but i see some pull's happening in the history, so maybe one is being re-run when the other isn't or smth. 

i don't see anything that explains the failure, having to do with the work here or otherwise... hopefully that succeeds on the next run.

**Comment by ceblanton** [comment]
Even though I'm still working on these, I think we should merge them in. As we are all updating docs today, we'll see more merge conflicts unless we merge more frequencly.

**Comment by ilaflott** [comment]
> Even though I'm still working on these, I think we should merge them in. As we are all updating docs today, we'll see more merge conflicts unless we merge more frequently.

still in draft mode! no one can merge it in, even with approval, if the PR is in draft mode.

**Review by ilaflott — APPROVED** [review]
assuming the check passes, i approve.

**Pull request merged**
