### PR TITLE
Include quotes in the rose-suite.conf values

### PR DESCRIPTION
**Pull request by ceblanton**
## Describe your changes
Recent updates to `fre pp configure-yaml` seem to require quotes to pass Cylc validation.

## Issue ticket number and link (if applicable)
#99

## Checklist before requesting a review

- [x] I ran my code
- [x] I tried to make my code readable
- [x] I tried to comment my code
- [ ] I wrote a new test, if applicable
- [ ] I wrote new instructions/documentation, if applicable
- [ ] I ran pytest and inspected it's output
- [ ] I ran pylint and attempted to implement some of it's feedback

### CODE REVIEW

**Comment by ilaflott** [comment]
this is the perfect candidate for a test. @cwhitlock-NOAA myself, and now presumably you and @singhd789 have all tripped over this.

**Comment by ceblanton** [comment]
Not ready, yet. Discovered some more quoting issues (booleans do not want to be quoted- arggg!)

**Review by singhd789 — COMMENTED** [review]
I forgot about the quotes! Good catch. I think we need to add a bit for `True` and `False` items though. I don't think those need to be in quotes

**Comment by ceblanton** [comment]
Ha! Yes, it was the booleans, you were exactly right

**Review by singhd789 — APPROVED** [review]

**Comment by ilaflott** [comment]
from the `pytest` suite-
```
fre/pp/tests/test_rose_quoting.py ..                                     [ 58%]
```

totally fab. totally gorg.

**Pull request merged**
