### PR TITLE
 Adding catalog documentation

### PR DESCRIPTION
**Pull request by Ciheim**
## Checklist before requesting a review

- [ ] I ran my code
- [ ] I tried to make my code readable
- [ ] I tried to comment my code
- [ ] I wrote a new test, if applicable
- [X] I wrote new instructions/documentation, if applicable
- [ ] I ran pytest and inspected it's output
- [ ] I ran pylint and attempted to implement some of it's feedback

### CODE REVIEW

**Comment by Ciheim** [comment]
#191

**Comment by ilaflott** [comment]
needs a quick merge with main to get the build to pass- this branch is a few dozen commits behind main.

**Comment by ceblanton** [comment]
Nice! It could use some improvement perhaps but it's pretty good already. OK to merge this to see the sphinx pipeline work?

**Comment by ilaflott** [comment]
i'm OK with a merge to see if the doc page works. seems like it should.

in the future, should we consider only accepting updates to the doc page from forks? if people use a fork they should be able to see a copy of the doc page under their github user namespace.

**Comment by ceblanton** [comment]
Thanks Ian, that's a big advantage for using forks (if that actually works- to draft publish the updates to the user github.io page). I'll give that a try.

**Review by ceblanton — APPROVED** [review]

**Comment by ceblanton** [comment]
Did this work?  The documentation pipeline appeared to run and succeed, but I don't see the updated words on

https://noaa-gfdl.github.io/fre-cli

**Comment by ilaflott** [comment]
> Thanks Ian, that's a big advantage for using forks (if that actually works- to draft publish the updates to the user github.io page). I'll give that a try.

i was hoping i hadn't deleted it yet and i did not- i have my fork from my developer-badges work still up. https://github.com/ilaflott/fre-cli/deployments/github-pages

i had to push to the main brain of my fork- not bad unless a developer wants to couple their doc-contribution to a code-contribution, in which case a distinct branch name and a change to the CI/CD logic should likely facilitate the scheme.

**Comment by ilaflott** [comment]
> Did this work? The documentation pipeline appeared to run and succeed, but I don't see the updated words on
> 
> https://noaa-gfdl.github.io/fre-cli

see https://noaa-gfdl.github.io/fre-cli/subtools.html

**Comment by ceblanton** [comment]
It's odd. For me I see the new text in the "view page source" but not the displayed page.

**Comment by Ciheim** [comment]
Same here...

**Comment by ceblanton** [comment]
Ciheim, did you see it display properly locally? I think you might be the few among us who can run sphinx-build manually.

**Comment by Ciheim** [comment]
Check  https://noaa-gfdl.github.io/fre-cli/subtools.html again. Seems like it decided to work now.

**Comment by ilaflott** [comment]
Screenshot 2024-10-01 at 12 27 52 PM
looks good to me....

**Comment by Ciheim** [comment]
Minus the code-snippet at the bottom, yes

**Comment by ilaflott** [comment]
```
.. code-block:: terminal
fre catalog buildcatalog --overwrite /archive/path_to_data_dir ~/output
```

seems wrong according to https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block 

I would this this should maybe be:
```
.. code-block:: bash
    fre catalog buildcatalog --overwrite /archive/path_to_data_dir ~/output
```

**Comment by Ciheim** [comment]
Should be 'console'

**Pull request merged**
