### PR TITLE
draft: Use git tag for python/conda package version

### PR DESCRIPTION
**Pull request by ceblanton**
Followed instructions on

https://github.com/jbweston/miniver

may resolve https://github.com/NOAA-GFDL/fre-cli/issues/109

### CODE REVIEW

**Comment by ilaflott** [comment]
What do we want to accomplish here?

Iterate version number every merge to `main`?

**Comment by ceblanton** [comment]
I think we want two deploying pipelines. One for versioned releases, that is triggered by creation of a new git tag. And the second for the testing release, that is triggered by pushes to `main`.

The part that I'd like from this PR is connecting the conda package version to the git tag version.

It doesn't work, for some reason. I'll change to draft and close it soon. I think replacing `setuptools` with `setuptools-scm` might be the most palatable solution to connect the conda package version to the git tag version.

**Comment by ilaflott** [comment]
are these PRs supposed to be drafts? are they still being worked on? the title having "draft" does not make this PR a draft.

**Comment by ilaflott** [comment]
closing for lack of activity

**Comment by ceblanton** [comment]
Thanks Ian. Agreed. It didn't work well enough to really propose it.

**Pull request closed without merging**
