### PR TITLE
Fix click bindings

### PR DESCRIPTION
**Pull request by ceblanton**
Fix, adjust some recent pylint-inspired changes to the import structure.

## Checklist before requesting a review

- [ ] I ran my code
- [ ] I tried to make my code readable
- [ ] I tried to comment my code
- [ ] I wrote a new test, if applicable
- [ ] I wrote new instructions/documentation, if applicable
- [ ] I ran pytest and inspected it's output
- [ ] I ran pylint and attempted to implement some of it's feedback

### CODE REVIEW

**Comment by ilaflott** [comment]
what is being fixed? what is the error?

**Comment by ceblanton** [comment]
an200:~%>fre pp wrapper --config-file /nbhome/c2b/git/am5xml/awg_include/am5.yaml --experiment c96L65_am5f7b12r1_amip --platform gfdl.ncrc5-intel23-classic --target prod-openmp

Traceback (most recent call last):
  File "/home/fms/local/opt/fre/2024.01/bin/fre", line 10, in <module>
    sys.exit(fre())
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nbhome/fms/conda/envs/fre-2024.01/lib/python3.9/site-packages/fre/pp/frepp.py", line 208, in wrapper
    context.forward(wrapper.runFre2pp)
AttributeError: 'Command' object has no attribute 'runFre2pp'

**Comment by ceblanton** [comment]
an200:~%>fre --version
fre, version 2024.1

And fre --version lost the leading zero again.. Though `fre pp checkout` was able to retrieve the correct one with your changes.

**Comment by ceblanton** [comment]
I convinced myself the change to the imports you made was the cause but I don't know.. click bindings are mysterious (to this person). it's no doubt almost working in any case.

**Comment by ilaflott** [comment]
the problem is the `click` cli command `fre pp wrapper` mapping directory to the import name, `fre.pp.wrapper`. This ends up making the `wrapper` call/function definition in `fre/pp/frepp.py` ambiguous to the python interpreter. `pylint` can see the issue!

```
$] pylint fre/pp
...
...
...
************* Module fre.pp.frepp
fre/pp/frepp.py:36:0: E0102: function already defined line 16 (function-redefined)
fre/pp/frepp.py:53:0: E0102: function already defined line 14 (function-redefined)
...
...
...
```

So if we change the import to, instead, `wrapper_script`, `click` forwards the context correctly and proceeds into the functions... and hits the next problem!

**Pull request closed without merging**
