### PR TITLE
Locate the experiment pp.yamls relative to the main yaml dir

### PR DESCRIPTION
**Pull request by ceblanton**
## Describe your changes
`fre pp configure-yaml` was unable to locate the child experiment pp.yaml. An update to prepend the directory containing the main yaml resolves the problem.

## Issue ticket number and link (if applicable)
#99 

## Checklist before requesting a review

- [x] I ran my code
- [x] I tried to make my code readable
- [x] I tried to comment my code
- [ ] I wrote a new test, if applicable
- [ ] I wrote new instructions/documentation, if applicable
- [ ] I ran pytest and inspected it's output
- [ ] I ran pylint and attempted to implement some of it's feedback

### CODE REVIEW

**Comment by ceblanton** [comment]
Tiny fix for locating the experiment yamls relative to the main yaml.

**Comment by ilaflott** [comment]
this pipeline's success depends on https://github.com/NOAA-GFDL/fre-cli/pull/140

**Comment by ilaflott** [comment]
> this pipeline's success depends on #140

actually, that's not quite true (yet). but intakebuilder will be deleted someday. the pipeline seemed to fail because the connection to the `conda-forge` channel seemed to die randomly. rerunning

**Comment by ceblanton** [comment]
Agreed. the pipeline fail was a weird one-off error related to conda-forge.

**Review by singhd789 — APPROVED** [review]

**Pull request merged**
